project_name: cert-manager-openshift-routes
before:
  hooks:
    - go test -v ./...
    - ./hack/generate-static-manifest.sh {{ .Version }}
builds:
  - id: cert-manager-openshift-routes
    main: ./internal/cmd
    binary: cert-manager-openshift-routes
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - riscv64
      - ppc64le
    goarm:
      - '6'
      - '7'
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
dockers:
  - id: cert-manager-openshift-routes-amd64
    goarch: amd64
    image_templates:
      - ghcr.io/poponealex/cert-manager-openshift-routes:{{ .Version }}-amd64
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-arm64
    goarch: arm64
    image_templates:
      - ghcr.io/poponealex/cert-manager-openshift-routes:{{ .Version }}-arm64
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/poponealex/cert-manager-openshift-routes:{{ .Version }}
    image_templates:
      - ghcr.io/poponealex/cert-manager-openshift-routes:{{ .Version }}-amd64
      - ghcr.io/poponealex/cert-manager-openshift-routes:{{ .Version }}-arm64
checksum:
  name_template: 'checksums.txt'
release:
  extra_files:
    - glob: ./cert-manager-openshift-routes-*.yaml
      name_template: cert-manager-openshift-routes.yaml