project_name: cert-manager-openshift-routes
before:
  hooks:
    - go test -v ./...
    # update static manifests
    - ./hack/generate-static-manifest.sh {{ .Version }}
    # update and package new Helm chart
    - helm package ./deploy/chart --version {{ trimprefix .Version "v"}} --app-version {{ .Version }}
    # upload Helm chart as OCI artifact to GitHub Container Registry
    - '{{if .IsSnapshot}}echo SKIPPING: {{end}}helm push ./openshift-routes-{{ trimprefix .Version "v"}}.tgz oci://ghcr.io/cert-manager/charts'

builds:
  - id: cert-manager-openshift-routes
    main: ./internal/cmd
    binary: cert-manager-openshift-routes
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - riscv64
      - ppc64le
    goarm:
      - "6"
      - "7"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
dockers:
  - id: cert-manager-openshift-routes-amd64
    goarch: amd64
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-amd64
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-arm64
    goarch: arm64
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-arm64
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-armv6
    goarch: arm
    goarm: "6"
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-armv6
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-armv7
    goarch: arm
    goarm: "7"
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-armv7
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-s390x
    goarch: s390x
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-s390x
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-riscv64
    goarch: riscv64
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-riscv64
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/riscv64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: cert-manager-openshift-routes-ppc64le
    goarch: ppc64le
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-ppc64le
    use: buildx
    dockerfile: internal/cmd/Dockerfile
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}
    image_templates:
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-amd64
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-arm64
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-armv6
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-armv7
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-s390x
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-riscv64
      - ghcr.io/cert-manager/cert-manager-openshift-routes:{{ .Version }}-ppc64le
checksum:
  name_template: "checksums.txt"
release:
  draft: true
  replace_existing_draft: true
  extra_files:
    - glob: ./cert-manager-openshift-routes-*.yaml
      name_template: cert-manager-openshift-routes.yaml
    - glob: ./openshift-routes-*.tgz
      name_template: openshift-routes-chart.tgz
