apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshift-routes.fullname" . }}
  namespace: {{ include "openshift-routes.namespace" . }}
  labels:
    {{- include "openshift-routes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "openshift-routes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openshift-routes.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openshift-routes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: openshift-routes
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "openshift-routes.image" (tuple .Values.image $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-v={{ .Values.logLevel }}"
            - "--leader-election-namespace={{ .Release.Namespace }}"
            - "--issuance-mode={{ .Values.issuanceMode }}"
          ports:
          - containerPort: 6060
            name: readiness
            protocol: TCP
          {{- if .Values.metrics.enabled }}
          - containerPort: 9402
            name: metrics
            protocol: TCP
          {{- end }}
          readinessProbe:
            httpGet:
              port: readiness
              path: "/readyz"
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
